### ISSUE TITLE
I'm gonna upload everything I have in code so far, either it is complete, it's incomplete or it may not be used

### ISSUE THREAD

**Issue by Dileyz** [THD-AI-2023/Devablos-Project#16]
I'm trying to upload the files and this thing wont allow me :c

**Comment by arudaev** [comment]
@Dileyz Please don't just upload them. Integrate them based on my specifications. Don't just upload them 😐

**Comment by Dileyz** [comment]
I understand, could you please explain me how am I supposed to integrate them? Like, where in github?

**Comment by arudaev** [comment]
Have you checked out the README.md file? @Dileyz

**Comment by Dileyz** [comment]
Yeah but the readme doesn't say anything about editing code on github, it just specifies our tasks. It's either that or I'm stupid. Or both

**Comment by arudaev** [comment]
Ok... I meant the dir structure, but okay. Let's meet tomorrow afternoon in plattling. I will help you with integration

**Comment by Dileyz** [comment]
Where and at what time? Like are you coming to my place or what's your plan?

**Comment by arudaev** [comment]
Well, I think this will be a good chance to visit plattling town square. So that is my plan. Along the way, I will tell you my location and I will help you. Is that okay. Or do you wanna just meet on Tuesday? @Dileyz

**Comment by Dileyz** [comment]
The town square is not too big, so if you want to work on the project we'll have to probably come to my place, but sure, either way I was planning to stay here and work

**Comment by arudaev** [comment]
Do you think I should go there today, tomorrow or should we just meet on Tuesday?

**Comment by Dileyz** [comment]
Tbh, I'm not sure, however fits you best, its not me the one who is moving, I'm fine with either choice

**Comment by arudaev** [comment]
Tell me what you already got, before I come there.

**Comment by Dileyz** [comment]
I have the whole react thingy (basically what you sent me in terms of content, not code [or at least that's what I think I have]) and I started to experiment with CSS to make a better design with the app (and also the HTML file that we are not using and some tests that aren't included in the file itself)
